name: tokenizer_parser
description: A dart package for creating parsers.
version: 0.1.0
repository: https://github.com/roadroot/tokenizer

environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
