name: tokenizer_parser
description: A dart package for creating parsers.
version: 0.1.1
repository: https://github.com/roadroot/tokenizer

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
